### PR TITLE
Reconnect corrections

### PR DESCRIPTION
**Pull request by elupus**
This attempts to fix reconnect when tunnels are lost. It should fix the issues reported in #19 .

### CODE REVIEW

**Comment by elupus** [comment]
There does seem to be a sort of indecision about the usage of exceptions or return values on errors.

Seems more logical to issue exceptions for error situations and using except/finally clauses to clean stuff up.

**Comment by open-homeautomation** [comment]
This pull request did not work at all. No connect was possible anymore. There was one obvious problem that "local_ip = self.control_socket.getsockname()" was used to get the local IP. However, this returns a tuple, not just the IP address. I guess, there are more bugs as fixing this did not help. Please go over your pull request again and test it before re-submitting. Unit tests can be tested with the "test.sh" script.

**Comment by elupus** [comment]
That was a typo indeed. Sorry about that, copy paste error from the system I tested on. I will investigate if there was something more lost.

**Comment by elupus** [comment]
Eh.. what the heck happened here!! You merged stuff into my branch and pushed to my github clone. Didn't even know you where allowed to push to my repo.

**Pull request merged**
